set directory=~/.tmp
set nobackup
set nowritebackup
set nu
set cursorline
set wrap
set showcmd
set wildmenu
set hlsearch
set incsearch
set ignorecase
set smartcase
syntax enable
colorscheme kolor
set hlsearch
exec "nohlsearch"
set guifont=Fira\ Code:h12

noremap K 5k
noremap J 5j


